/**
 * @file PoseArray.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/PoseArray` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_POSEARRAY_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_POSEARRAY_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Pose.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/PoseArray` message.
      struct PoseArray
      {
        static constexpr const char *TYPE = "geometry_msgs/PoseArray";
        static constexpr const char *MD5 = "916c28c5764443f268b296bb671b9d97";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\ngeometry_msgs/Pose[] poses\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n================================================================================\nMSG: geometry_msgs/Pose\ngeometry_msgs/Point position\ngeometry_msgs/Quaternion orientation\n================================================================================\nMSG: geometry_msgs/Point\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<::limxsdk::msg::geometry_msgs::Pose> poses;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readMsgArray(poses))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writeMsgArray(poses))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 4;
          total += header.encodedSize();
          total += ::limxsdk::codec::arraySize(poses);
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 4 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_POSEARRAY_H_
