/**
 * @file TwistStamped.h
 *
 * @brief Generated mirror of the mros `geometry_msgs/TwistStamped` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_GEOMETRY_MSGS_TWISTSTAMPED_H_
#define _LIMX_SDK_MSG_GEOMETRY_MSGS_TWISTSTAMPED_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/geometry_msgs/Twist.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace geometry_msgs
    {
      /// @brief Mirror of the mros `geometry_msgs/TwistStamped` message.
      struct TwistStamped
      {
        static constexpr const char *TYPE = "geometry_msgs/TwistStamped";
        static constexpr const char *MD5 = "98d34b0043a2093cf9d9345ab6eef12e";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\ngeometry_msgs/Twist twist\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n================================================================================\nMSG: geometry_msgs/Twist\ngeometry_msgs/Vector3 linear\ngeometry_msgs/Vector3 angular\n================================================================================\nMSG: geometry_msgs/Vector3\nfloat64 x\nfloat64 y\nfloat64 z\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        ::limxsdk::msg::geometry_msgs::Twist twist;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!twist.decode(reader))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!twist.encode(writer))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 0;
          total += header.encodedSize();
          total += twist.encodedSize();
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 0 + ::limxsdk::msg::std_msgs::Header::minEncodedSize() + ::limxsdk::msg::geometry_msgs::Twist::minEncodedSize();
        }
      };
    } // namespace geometry_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_GEOMETRY_MSGS_TWISTSTAMPED_H_
