/**
 * @file JointState.h
 *
 * @brief Generated mirror of the mros `sensor_msgs/JointState` message.
 *
 * THIS FILE IS GENERATED BY tools/limxsdk-gen/limxsdk_gen.py - DO NOT EDIT.
 * Regenerate it instead of patching it; hand edits are lost on the next run.
 *
 * © [2025] LimX Dynamics Technology Co., Ltd. All rights reserved.
 */

#ifndef _LIMX_SDK_MSG_SENSOR_MSGS_JOINTSTATE_H_
#define _LIMX_SDK_MSG_SENSOR_MSGS_JOINTSTATE_H_

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "limxsdk/codec/codec.h"
#include "limxsdk/msg/std_msgs/Header.h"

namespace limxsdk
{
  namespace msg
  {
    namespace sensor_msgs
    {
      /// @brief Mirror of the mros `sensor_msgs/JointState` message.
      struct JointState
      {
        static constexpr const char *TYPE = "sensor_msgs/JointState";
        static constexpr const char *MD5 = "3066dcd76a6cfaef579bd0f34173e9fd";

        /// @brief ROS concatenated definition, as reported by mros.
        static const char *definition() { return "std_msgs/Header header\nstring[] name\nfloat64[] position\nfloat64[] velocity\nfloat64[] effort\n================================================================================\nMSG: std_msgs/Header\nuint32 seq\ntime stamp\nstring frame_id\n"; }

        ::limxsdk::msg::std_msgs::Header header;
        std::vector<std::string> name;
        std::vector<double> position;
        std::vector<double> velocity;
        std::vector<double> effort;

        /// @brief Decode one frame; false means discard the whole message.
        bool decode(::limxsdk::codec::Reader &reader)
        {
          if (!header.decode(reader))
          {
            return false;
          }
          if (!reader.readValueArray(name, 4))
          {
            return false;
          }
          if (!reader.readPodArray(position))
          {
            return false;
          }
          if (!reader.readPodArray(velocity))
          {
            return false;
          }
          if (!reader.readPodArray(effort))
          {
            return false;
          }
          return !reader.failed();
        }

        /// @brief Encode into a buffer of at least encodedSize() bytes.
        bool encode(::limxsdk::codec::Writer &writer) const
        {
          if (!header.encode(writer))
          {
            return false;
          }
          if (!writer.writeValueArray(name))
          {
            return false;
          }
          if (!writer.writePodArray(position))
          {
            return false;
          }
          if (!writer.writePodArray(velocity))
          {
            return false;
          }
          if (!writer.writePodArray(effort))
          {
            return false;
          }
          return !writer.failed();
        }

        /// @brief Exact number of bytes encode() will write.
        std::size_t encodedSize() const
        {
          std::size_t total = 16;
          total += header.encodedSize();
          total += ::limxsdk::codec::arraySize(name);
          total += position.size() * 8;
          total += velocity.size() * 8;
          total += effort.size() * 8;
          return total;
        }

        /// @brief Smallest possible encoding, used to reject bogus array lengths.
        static std::size_t minEncodedSize()
        {
          return 16 + ::limxsdk::msg::std_msgs::Header::minEncodedSize();
        }
      };
    } // namespace sensor_msgs
  } // namespace msg
} // namespace limxsdk

#endif // _LIMX_SDK_MSG_SENSOR_MSGS_JOINTSTATE_H_
